apiVersion: v1
kind: Service
metadata:
  name: gateway-nginx-service
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  selector:
    app: gateway-nginx-api-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort