apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-nginx-deployment
spec:
  replicas: 1   # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: gateway-nginx-api-app
  template:
    metadata:
      labels:
        app: gateway-nginx-api-app
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent   # Set the image pull policy
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: gateway-nginx-app-config
