apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-nginx-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-nginx-api-app
  template:
    metadata:
      labels:
        app: gateway-nginx-api-app
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: gateway-nginx-api-container
          image: ilyagrigoryan/gateway-nginx-api-image
          imagePullPolicy: IfNotPresent   # Set the image pull policy
          ports:
            - containerPort: 80
