apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api-docker
  template:
    metadata:
      labels:
        app: sample-api-docker
    spec:
      containers:
        - name: sample-api-docker
          image: sample-api-docker
          imagePullPolicy: IfNotPresent   # Set the image pull policy
          ports:
            - containerPort: 80
