apiVersion: v1
kind: Service
metadata:
  name: sample-jk8s-api-service
spec:
  selector:
    app: sample-jk8s-api-docker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort   # Use NodePort type to expose externally
